# action.yml
name: 'Pylint'
description: 'Pylint action in docker'
inputs:
  pylint-input-args:  # id of input
    description: 'input args to run pylint'
    required: true
    default: 'pylint --help'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pylint-input-args }}
    